---
title: "Models comparison"
author: "Saul Pierotti"
output: 
  pdf_document:
    latex_engine: lualatex
---

```{r imports}
modules <- list.files(path = "utils", full.names = TRUE)
sapply(modules, source)
```

# Plots

```{r single protein models performance comparison plot, dev="tikz", results="hide"}
plot <-
  get_performance_comparison_plot(
    single_protein_comparison_tb %>% filter(method == "pearson")
    ) +
  ylab("Pearson correlation coefficient")

print(plot)

# create_tikz(plot,
#             "single_protein_models_performance_comparison.tex",
#             3,
#             latex_textwidth)
```

```{r single protein naive performance pearson confidence intervals}
print("Naive, Pearson")
get_corr_bootstrap(
  test_result_naive_tb  %>% filter(kind == "test"),
  method = "pearson",
  n_reps = 10000
)
```

```{r single protein naive performance spearman confidence intervals}
print("Naive, Spearman")
get_corr_bootstrap(test_result_naive_tb  %>% filter(kind == "test"),
                   method = "spearman",
                   n_reps = 10000)
```

```{r single protein by position performance pearson confidence intervals}
print("By position, Pearson")
get_corr_bootstrap(
  test_result_by_position_tb %>% filter(kind == "test"),
  method = "pearson",
  n_reps = 10000
)
```

```{r single protein by position performance spearman confidence intervals}
print("By position, Spearman")
get_corr_bootstrap(test_result_by_position_tb  %>% filter(kind == "test"),
                   method = "spearman",
                   n_reps = 10000)
```

```{r general xgb performance spearman confidence intervals}
print("LOPO, Spearman")
get_corr_bootstrap(test_result_lopo_xgb_tb %>% filter(kind == "test"),
                   method = "spearman",
                   n_reps = 10000)
```

```{r single protein models performance comparison plot, dev="tikz", results="hide"}
plot <-
  get_performance_comparison_plot(
    xgb_models_comparison_tb %>% filter(method == "spearman") %>%
      mutate(model = fct_recode(model, "LOPO" = "lopo_models_xgb")) %>%
      mutate(model = fct_relevel(model, c(
        "naive", "by_position", "LOPO"
      )))
  ) +
  ylab("Spearman correlation coefficient")

plot_presentation <-
  get_performance_comparison_plot(
    xgb_models_comparison_tb %>% filter(method == "spearman") %>%
      mutate(model = fct_recode(model, "LOPO" = "lopo_models_xgb")) %>%
      mutate(model = fct_relevel(model, c(
        "naive", "by_position", "LOPO"
      ))),
    use_outline = TRUE,
    size = 1.3,
    dodge_width = 0.3
  ) +
  ylab("Spearman correlation coefficient") +
  scale_fill_manual(values = bologna_palette,
                     name = "Model",
                     labels = models_labels)

print(plot)
print(plot_presentation)

# create_tikz(plot,
#             "xgb_models_performance_comparison.tex",
#             3,
#             latex_textwidth)

create_tikz(plot_presentation,
            "presentation_xgb_models_performance_comparison.tex",
            latex_beamer_height*0.75,
            latex_beamer_width)
```

```{r general models performance comparison plot, dev="tikz", results="hide"}
source("./utils/functions.R")
source("./utils/constants.R")

plot <-
  get_performance_comparison_plot(
    general_models_corr_tb %>% filter(method=="spearman")
    ) +
  ylab("Spearman correlation coefficient")

plot_presentation <-
  get_performance_comparison_plot(
    general_models_corr_tb %>% filter(method=="spearman"),
    use_outline = TRUE,
    size = 1.3,
    dodge_width = 0.3
    ) +
  ylab("Spearman correlation coefficient") +
  scale_fill_manual(values = bologna_palette,
                    name = "Model",
                    labels = models_labels) +
  guides(fill = guide_legend(nrow = 2)) +
  theme(legend.position = "top")

print(plot)
print(plot_presentation)

# create_tikz(plot,
#             "general_models_performance_comparison.tex",
#             latex_textheight * 0.5,
#             latex_textwidth)

create_tikz(plot_presentation,
            "presentation_general_models_performance_comparison.tex",
            latex_beamer_height*0.8,
            latex_beamer_width*0.6)
```


```{r general model differences significance, dev="tikz", results="hide"}
get_general_models_corr_significance(general_models_rank_tb, n_reps=10000)
```
